server.port: 8761
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

my:
  greeting: Hello
  values: Testing

app:
  name: My app
  description: Testing Configuration with YAML


db.host: 192.16.0.2
db.port: 8232
db.connection: "https://conection.mysql.com/testdb"



management.endpoints.web.exposure.include: "*"
